import type { Listing, ListingStatus, VerificationBadge } from '@/types/nyumba';

export const formatKes = (amount: number) => `KES ${amount.toLocaleString('en-KE')}`;

export const STATUS_META: Record<
    ListingStatus,
    { label: string; tip: string; className: string }
> = {
    confirmed: {
        label: 'Community Confirmed',
        tip: 'At least one community member reported this home as vacant after a recent physical visit.',
        className: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    },
    vacated: {
        label: 'Recently Vacated',
        tip: 'A former tenant reported moving out of this home recently.',
        className: 'bg-amber-50 text-amber-700 border-amber-200',
    },
    upcoming: {
        label: 'Upcoming Vacancy',
        tip: 'The current tenant says they plan to move out on a stated date.',
        className: 'bg-sky-50 text-sky-700 border-sky-200',
    },
    reconfirm: {
        label: 'Needs Reconfirmation',
        tip: 'No community member has confirmed this report recently.',
        className: 'bg-stone-100 text-stone-600 border-stone-200',
    },
    occupied: {
        label: 'Possibly Occupied',
        tip: 'Someone reported that this home may already be taken.',
        className: 'bg-red-50 text-red-700 border-red-200',
    },
};

export const VERIFICATION_META: Record<
    VerificationBadge,
    { label: string; tip: string; className: string }
> = {
    phone: {
        label: 'Phone Verified',
        tip: 'This contributor confirmed a Kenyan phone number with a one-time code.',
        className: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    },
    id: {
        label: 'Identity Verified',
        tip: 'The contributor completed optional ID and selfie verification. Documents are never shown publicly.',
        className: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    },
    tenant: {
        label: 'Verified Former Tenant',
        tip: 'Private evidence of past occupancy was reviewed by NyumbaHub moderators.',
        className: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    },
    evidence: {
        label: 'Evidence Provided',
        tip: 'Photos or a blurred document were attached to this report.',
        className: 'bg-sky-50 text-sky-700 border-sky-200',
    },
    multi: {
        label: 'Multiple Confirmations',
        tip: 'Two or more community members confirmed after separate visits.',
        className: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    },
    updated: {
        label: 'Recently Updated',
        tip: 'Rent, condition or availability was changed in the last 7 days.',
        className: 'bg-amber-50 text-amber-700 border-amber-200',
    },
    review: {
        label: 'Under Review',
        tip: 'A moderator is checking this report before it is fully published.',
        className: 'bg-stone-100 text-stone-600 border-stone-200',
    },
};

// Cycled across listing card photos until real uploads are wired up.
export const PLACEHOLDER_PHOTOS = [
    '/images/hse_1.jpg',
    '/images/hse_2.jpg',
    '/images/hse_3.webp',
];

// Mock data matching the shape of nyumbahub.html's LISTINGS array.
// Replace with real Eloquent-backed props once the API is wired up.
export const MOCK_LISTINGS: Listing[] = [
    {
        id: 'L1',
        type: '1-Bedroom',
        estate: 'Ruaka',
        town: 'Kiambu',
        county: 'Kiambu',
        title: 'Recently vacated 1-bedroom in Ruaka near Two Rivers',
        rent: 22000,
        deposit: 22000,
        status: 'vacated',
        reported: '2 days ago',
        confirmed: 'Yesterday at 4:15 PM',
        beds: 1,
        baths: 1,
        parking: 'Available',
        water: 'Reliable',
        security: 'Good',
        rating: 4.2,
        savedCount: 0,
        photos: 9,
        video: true,
        badges: ['tenant', 'evidence', 'phone'],
        near: 'Ruaka stage, 7-min walk',
        note: 'The house has good natural light and the caretaker responds quickly. Water was mostly reliable, though there were occasional morning shortages during dry months. Electricity is prepaid. Ask about garbage charges before paying.',
    },
    {
        id: 'L2',
        type: 'Bedsitter',
        estate: 'South B',
        town: 'Nairobi',
        county: 'Nairobi',
        title: 'Bedsitter reported vacant in South B, Mariakani side',
        rent: 11500,
        deposit: 11500,
        status: 'confirmed',
        reported: '4 days ago',
        confirmed: '6 hours ago',
        beds: 0,
        baths: 1,
        parking: 'None',
        water: 'Very reliable',
        security: 'Very good',
        rating: 4.5,
        savedCount: 38,
        photos: 7,
        video: false,
        badges: ['tenant', 'multi', 'evidence'],
        near: 'Mariakani stage, 4-min walk',
        note: 'Quiet plot with a resident caretaker and borehole backup. Rent was paid before the 5th. Water bill was shared monthly, around KES 500.',
    },
    {
        id: 'L3',
        type: 'Studio',
        estate: 'Kilimani',
        town: 'Nairobi',
        county: 'Nairobi',
        title: 'Studio apartment reported vacated off Argwings Kodhek',
        rent: 34000,
        deposit: 34000,
        status: 'reconfirm',
        reported: '19 days ago',
        confirmed: '12 days ago',
        beds: 0,
        baths: 1,
        parking: 'Available',
        water: 'Reliable',
        security: 'Excellent',
        rating: 4.0,
        savedCount: 21,
        photos: 12,
        video: true,
        badges: ['id', 'evidence'],
        near: 'Yaya stage, 9-min walk',
        note: 'Great security with CCTV and a manned gate. Service charge is separate — confirm it before signing anything.',
    },
    {
        id: 'L4',
        type: '2-Bedroom',
        estate: 'Kasarani',
        town: 'Nairobi',
        county: 'Nairobi',
        title: '2-bedroom reported vacated in Kasarani, Sunton',
        rent: 19000,
        deposit: 19000,
        status: 'confirmed',
        reported: '6 days ago',
        confirmed: '2 days ago',
        beds: 2,
        baths: 2,
        parking: 'Available',
        water: 'Fair',
        security: 'Good',
        rating: 3.8,
        savedCount: 54,
        photos: 8,
        video: false,
        badges: ['tenant', 'phone'],
        near: 'Sunton stage, 5-min walk',
        note: 'Spacious for the price. Water rationing on some Tuesdays, so the tank matters. Matatus are easy to get before 8pm.',
    },
    {
        id: 'L5',
        type: 'Bedsitter',
        estate: 'Rongai',
        town: 'Kajiado',
        county: 'Kajiado',
        title: 'Bedsitter in Rongai reported vacant near Maasai Mall',
        rent: 9000,
        deposit: 9000,
        status: 'upcoming',
        reported: '1 day ago',
        confirmed: 'Not yet confirmed',
        beds: 0,
        baths: 1,
        parking: 'None',
        water: 'Fair',
        security: 'Fair',
        rating: 3.5,
        savedCount: 12,
        photos: 5,
        video: false,
        badges: ['phone', 'evidence'],
        near: 'Rongai stage, 11-min walk',
        note: 'Affordable and close to shops. I am moving out at the end of the month, so plan your visit after that date.',
    },
    {
        id: 'L6',
        type: '1-Bedroom',
        estate: 'Embakasi',
        town: 'Nairobi',
        county: 'Nairobi',
        title: '1-bedroom reported vacated in Embakasi, Pipeline edge',
        rent: 14000,
        deposit: 14000,
        status: 'occupied',
        reported: '11 days ago',
        confirmed: '3 days ago',
        beds: 1,
        baths: 1,
        parking: 'None',
        water: 'Reliable',
        security: 'Fair',
        rating: 3.4,
        savedCount: 9,
        photos: 6,
        video: false,
        badges: ['phone'],
        near: 'Pipeline stage, 3-min walk',
        note: 'Very convenient for transport but noisy at night. A visitor reported the unit may now be taken — please reconfirm at the gate.',
    },
];